import { colors, fontFamily, radius, spacing, typography } from "@codeaudit/ui/theme/tokens";
import { StyleSheet } from "react-native";

export const theme = {
  colors,
  radius,
  spacing,
  typography,
  fontFamily,
};

export const sharedStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.canvas,
  },
  screenPadded: {
    flex: 1,
    backgroundColor: colors.canvas,
    padding: spacing.xl,
    gap: spacing.md,
  },
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.canvas,
  },
  heroTitle: {
    fontFamily,
    fontSize: typography.displayLg.fontSize,
    fontWeight: typography.displayLg.fontWeight,
    lineHeight: typography.displayLg.fontSize * typography.displayLg.lineHeight,
    letterSpacing: typography.displayLg.letterSpacing,
    color: colors.ink,
  },
  headingLg: {
    fontFamily,
    fontSize: typography.headingLg.fontSize,
    fontWeight: typography.headingLg.fontWeight,
    lineHeight: typography.headingLg.fontSize * typography.headingLg.lineHeight,
    letterSpacing: typography.headingLg.letterSpacing,
    color: colors.ink,
  },
  headingSm: {
    fontFamily,
    fontSize: typography.headingSm.fontSize,
    fontWeight: typography.headingSm.fontWeight,
    lineHeight: typography.headingSm.fontSize * typography.headingSm.lineHeight,
    color: colors.ink,
  },
  cardTitle: {
    fontFamily,
    fontSize: typography.cardTitle.fontSize,
    fontWeight: typography.cardTitle.fontWeight,
    lineHeight: typography.cardTitle.fontSize * typography.cardTitle.lineHeight,
    color: colors.ink,
  },
  subtitle: {
    fontFamily,
    fontSize: typography.subtitle.fontSize,
    fontWeight: typography.subtitle.fontWeight,
    lineHeight: typography.subtitle.fontSize * typography.subtitle.lineHeight,
    color: colors.steel,
  },
  body: {
    fontFamily,
    fontSize: typography.bodyMd.fontSize,
    fontWeight: typography.bodyMd.fontWeight,
    lineHeight: typography.bodyMd.fontSize * typography.bodyMd.lineHeight,
    color: colors.charcoal,
  },
  label: {
    fontFamily,
    fontSize: typography.bodySmMedium.fontSize,
    fontWeight: typography.bodySmMedium.fontWeight,
    lineHeight: typography.bodySmMedium.fontSize * typography.bodySmMedium.lineHeight,
    color: colors.ink,
  },
  muted: {
    fontFamily,
    fontSize: typography.bodySm.fontSize,
    fontWeight: typography.bodySm.fontWeight,
    lineHeight: typography.bodySm.fontSize * typography.bodySm.lineHeight,
    color: colors.steel,
  },
  input: {
    fontFamily,
    height: 40,
    borderWidth: 1,
    borderColor: colors.hairline,
    borderRadius: radius.md,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    fontSize: typography.bodyMd.fontSize,
    color: colors.ink,
    backgroundColor: colors.canvas,
  },
  buttonPrimary: {
    fontFamily,
    backgroundColor: colors.primary,
    paddingVertical: 11,
    paddingHorizontal: spacing.xl,
    borderRadius: radius.full,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonPrimaryText: {
    fontFamily,
    color: colors.onPrimary,
    fontSize: typography.buttonMd.fontSize,
    fontWeight: typography.buttonMd.fontWeight,
    lineHeight: typography.buttonMd.fontSize * typography.buttonMd.lineHeight,
  },
  buttonSecondary: {
    fontFamily,
    borderWidth: 1,
    borderColor: colors.ink,
    backgroundColor: "transparent",
    paddingVertical: 11,
    paddingHorizontal: spacing.xl,
    borderRadius: radius.full,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonSecondaryText: {
    fontFamily,
    color: colors.ink,
    fontSize: typography.buttonMd.fontSize,
    fontWeight: typography.buttonMd.fontWeight,
    lineHeight: typography.buttonMd.fontSize * typography.buttonMd.lineHeight,
  },
  buttonOutline: {
    fontFamily,
    borderWidth: 1,
    borderColor: colors.hairline,
    backgroundColor: colors.canvas,
    paddingVertical: 11,
    paddingHorizontal: spacing.xl,
    borderRadius: radius.full,
    alignItems: "center",
    justifyContent: "center",
  },
  buttonOutlineText: {
    fontFamily,
    color: colors.ink,
    fontSize: typography.buttonMd.fontSize,
    fontWeight: typography.buttonMd.fontWeight,
    lineHeight: typography.buttonMd.fontSize * typography.buttonMd.lineHeight,
  },
  card: {
    borderWidth: 1,
    borderColor: colors.hairline,
    borderRadius: radius.xl,
    padding: spacing.xl,
    backgroundColor: colors.canvas,
    gap: spacing.xs,
  },
  cardSurface: {
    borderRadius: radius.xl,
    padding: spacing.xl,
    backgroundColor: colors.surface,
    gap: spacing.xs,
  },
  productCardCoral: {
    borderRadius: radius.hero,
    padding: spacing.xxl,
    backgroundColor: colors.brandCoral,
  },
  productCardMagenta: {
    borderRadius: radius.hero,
    padding: spacing.xxl,
    backgroundColor: colors.brandMagenta,
  },
  productCardBlue: {
    borderRadius: radius.hero,
    padding: spacing.xxl,
    backgroundColor: colors.brandBlue,
  },
  productCardPurple: {
    borderRadius: radius.hero,
    padding: spacing.xxl,
    backgroundColor: colors.brandPurple,
  },
  productCardText: {
    fontFamily,
    fontSize: typography.headingLg.fontSize,
    fontWeight: typography.headingLg.fontWeight,
    color: colors.onDark,
  },
  productCardSubtext: {
    fontFamily,
    fontSize: typography.bodySm.fontSize,
    color: "rgba(255,255,255,0.8)",
    marginTop: spacing.xs,
  },
  errorText: {
    fontFamily,
    color: colors.error,
    fontSize: typography.bodySm.fontSize,
  },
  successText: {
    fontFamily,
    color: colors.successText,
    fontSize: typography.bodySm.fontSize,
  },
  buttonDisabled: {
    opacity: 0.5,
  },
  buttonPressed: {
    opacity: 0.85,
  },
  row: {
    flexDirection: "row",
    gap: spacing.xs,
    flexWrap: "wrap",
  },
});
